data_cfg:
  representation: graph
  data_root: "{CHEMVL_DATA_ROOT}/pretraining_datasets/"
  paths:
    train_images_root: null
    val_images_root: null
    test_images_root: null
    train_data_file: 10M-106mds/train_data/data_list/train.txt
    val_data_file: 10M-106mds/test_data/data_list/test.txt
    test_data_file: 10M-106mds/test_data/data_list/test.txt
  graph_metadata_file: 10M-106mds/mds.csv
  train_dataloder_cfg:
    num_workers: 8
    batch_size: 64
    shuffle: true
  eval_dataloder_cfg:
    num_workers: 8
    batch_size: 32
    shuffle: false
runner_cfg:
  output_dir: results/pretraining/10M-106mds-graph-gcn
  multi_task_scheme: random
  optimizer_and_scheduler_cfg:
    param_dict_cfg:
      lr_prompt_learner_context: 0.0001
      lr_prompt_learner_ranks: 0.0001
      lr_image_encoder: 0.0
      lr_graph_encoder: 0.0001
      lr_text_encoder: 0.0
      lr_logit_scale: 0.0
      staged_lr_image_encoder:
        new_layers: []
        base_lr_mult: 1.0
        new_lr_mult: 1.0
    optimizer_cfg:
      optimizer_name: radam
      lr: 0.0001
      weight_decay: 0.0
      momentum: 0.9
      sgd_dampening: 0.0
      sgd_nesterov: false
      rmsprop_alpha: 0.99
      adam_beta1: 0.9
      adam_beta2: 0.999
      staged_lr: null
      lookahead: false
    lr_scheduler_cfg:
      lr_scheduler_name: multi_step
      stepsize:
        - 60
      gamma: 0.1
      max_epochs: 100
      warmup_epoch: 0
      warmup_cons_lr: 1.0e-05
      warmup_min_lr: 1.0e-05
      warmup_type: constant
      warmup_recount: true
  model_cfg:
    type: GraphOrdinalCLIPForMultiTask
    prompt_learner_cfg:
      type: PlainPromptLearner
      num_tasks: 106
      num_ranks:
        - 121
        - 153
        - 444
        - 297
        - 91
        - 297
        - 61
        - 53
        - 83
        - 443
        - 110
        - 884
        - 448
        - 297
        - 89
        - 297
        - 297
        - 37
        - 89
        - 89
        - 29
        - 21
        - 94
        - 27
        - 52
        - 37
        - 37
        - 109
        - 109
        - 13
        - 13
        - 45
        - 211
        - 109
        - 65
        - 34
        - 51
        - 23
        - 27
        - 25
        - 35
        - 25
        - 120
        - 140
        - 216
        - 14
        - 41
        - 33
        - 13
        - 13
        - 5
        - 53
        - 3
        - 160
        - 5
        - 4
        - 26
        - 71
        - 119
        - 17
        - 22
        - 231
        - 126
        - 13
        - 21
        - 108
        - 9
        - 6
        - 51
        - 51
        - 17
        - 25
        - 71
        - 31
        - 41
        - 25
        - 13
        - 11
        - 13
        - 13
        - 9
        - 76
        - 52
        - 52
        - 29
        - 29
        - 25
        - 16
        - 51
        - 1
        - 27
        - 62
        - 49
        - 17
        - 10
        - 17
        - 9
        - 15
        - 8
        - 33
        - 359
        - 108
        - 654
        - 439
        - 124
        - 413
      num_base_ranks: 3
      num_tokens_per_rank: 1
      num_context_tokens: 10
      rank_tokens_position: tail
      init_rank_path: null
      init_context: null
      rank_specific_context: false
      interpolation_type: linear
    text_encoder_name: RN50
    graph_encoder_cfg:
      type: MolCLRGCN
      num_layer: 5
      emb_dim: 300
      feat_dim: 512
      drop_ratio: 0.1
      pool: mean
trainer_cfg:
  precision: 16
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  fast_dev_run: false
multitask: true
