data_cfg:
  data_root: "{CHEMVL_DATA_ROOT}/pretraining_datasets/"
  paths:
    train_images_root: images-1M@224px/train_data
    val_images_root: images-1M@224px/test_data
    test_images_root: images-1M@224px/test_data
    train_data_file: 1M-106mds/train_data/data_list/train_mini.txt
    val_data_file: 1M-106mds/test_data/data_list/test_mini.txt
    test_data_file: 1M-106mds/test_data/data_list/test_mini.txt
  train_dataloder_cfg:
    num_workers: 4
    batch_size: 64
    shuffle: true
  eval_dataloder_cfg:
    num_workers: 4
    batch_size: 16
    shuffle: false
runner_cfg:
  output_dir: results/pretraining/1M-106mds-mini
  multi_task_scheme: random
  model_cfg:
    type: OrdinalCLIPForMultiTask
    prompt_learner_cfg:
      type: PlainPromptLearner
      num_tasks: 106
      num_ranks:
        - 81
        - 146
        - 265
        - 97
        - 53
        - 97
        - 61
        - 40
        - 61
        - 246
        - 97
        - 297
        - 300
        - 97
        - 53
        - 97
        - 97
        - 31
        - 52
        - 52
        - 20
        - 10
        - 94
        - 21
        - 28
        - 31
        - 31
        - 68
        - 68
        - 8
        - 8
        - 30
        - 175
        - 62
        - 32
        - 34
        - 15
        - 16
        - 21
        - 9
        - 9
        - 9
        - 103
        - 104
        - 65
        - 9
        - 34
        - 27
        - 9
        - 6
        - 3
        - 41
        - 3
        - 119
        - 5
        - 3
        - 9
        - 32
        - 97
        - 7
        - 12
        - 103
        - 19
        - 8
        - 14
        - 11
        - 5
        - 4
        - 51
        - 51
        - 5
        - 7
        - 34
        - 8
        - 19
        - 10
        - 10
        - 7
        - 13
        - 9
        - 5
        - 17
        - 28
        - 28
        - 28
        - 28
        - 12
        - 16
        - 11
        - 1
        - 13
        - 62
        - 25
        - 7
        - 9
        - 9
        - 5
        - 7
        - 4
        - 15
        - 269
        - 13
        - 365
        - 174
        - 119
        - 265
      num_base_ranks: 3
      num_tokens_per_rank: 1
      num_context_tokens: 10
      rank_tokens_position: tail
      init_rank_path: null
      init_context: null
      rank_specific_context: false
      interpolation_type: linear
    text_encoder_name: RN50
    image_encoder_name: RN50
multitask: true

