from rdkit import Chem
from rdkit.Chem import Descriptors
import clip


class PriorKnowledgeLib(object):
    def __init__(self, version='v2_107'):
        super().__init__()
        keys_from_rdkit_v1 = [
            'HeavyAtomCount',
            'MolLogP',
            'MolMR',
        ]

        keys_from_rdkit_v2_107 = [
            'MolWt',
            'TPSA',
            'HeavyAtomCount',
            'MolLogP',
            'MolMR',
            'NHOHCount',
            'NOCount',
            'NumAliphaticCarbocycles',
            'NumAliphaticHeterocycles',
            'NumAliphaticRings',
            'NumAromaticCarbocycles',
            'NumAromaticHeterocycles',
            'NumAromaticRings',
            'NumHAcceptors',
            'NumHDonors',
            'NumHeteroatoms',
            'NumRadicalElectrons',
            'NumRotatableBonds',
            'NumSaturatedCarbocycles',
            'NumSaturatedHeterocycles',
            'NumSaturatedRings',
            'RingCount',
            'fr_Al_COO',
            'fr_Al_OH',
            'fr_Al_OH_noTert',
            'fr_ArN',
            'fr_Ar_COO',
            'fr_Ar_N',
            'fr_Ar_NH',
            'fr_Ar_OH',
            'fr_COO',
            'fr_COO2',
            'fr_C_O',
            'fr_C_O_noCOO',
            'fr_C_S',
            'fr_HOCCN',
            'fr_Imine',
            'fr_NH0',
            'fr_NH1',
            'fr_NH2',
            'fr_N_O',
            'fr_Ndealkylation1',
            'fr_Ndealkylation2',
            'fr_Nhpyrrole',
            'fr_SH',
            'fr_aldehyde',
            'fr_alkyl_carbamate',
            'fr_alkyl_halide',
            'fr_allylic_oxid',
            'fr_amide',
            'fr_amidine',
            'fr_aniline',
            'fr_aryl_methyl',
            'fr_azide',
            'fr_azo',
            'fr_barbitur',
            'fr_benzene',
            'fr_benzodiazepine',
            'fr_bicyclic',
            'fr_diazo',
            'fr_dihydropyridine',
            'fr_epoxide',
            'fr_ester',
            'fr_ether',
            'fr_furan',
            'fr_guanido',
            'fr_halogen',
            'fr_hdrzine',
            'fr_hdrzone',
            'fr_imidazole',
            'fr_imide',
            'fr_isocyan',
            'fr_isothiocyan',
            'fr_ketone',
            'fr_ketone_Topliss',
            'fr_lactam',
            'fr_lactone',
            'fr_methoxy',
            'fr_morpholine',
            'fr_nitrile',
            'fr_nitro',
            'fr_nitro_arom',
            'fr_nitro_arom_nonortho',
            'fr_nitroso',
            'fr_oxazole',
            'fr_oxime',
            'fr_para_hydroxylation',
            'fr_phenol',
            'fr_phenol_noOrthoHbond',
            'fr_phos_acid',
            'fr_phos_ester',
            'fr_piperdine',
            'fr_piperzine',
            'fr_priamide',
            'fr_prisulfonamd',
            'fr_pyridine',
            'fr_quatN',
            'fr_sulfide',
            'fr_sulfonamd',
            'fr_sulfone',
            'fr_term_acetylene',
            'fr_tetrazole',
            'fr_thiazole',
            'fr_thiocyan',
            'fr_thiophene',
            'fr_unbrch_alkane',
            'fr_urea'
        ]

        keys_from_rdkit_all = [name for name, _ in Descriptors.descList]

        self.version = version
        if self.version == 'v1_3':
            self.prior_keys = keys_from_rdkit_v1
        elif self.version == 'v1_105':
            self.prior_keys = keys_from_rdkit_v1
        elif self.version == 'v2_107':
            self.prior_keys = keys_from_rdkit_v2_107
        elif self.version == 'all':
            self.prior_keys = keys_from_rdkit_all
        else:
            raise ValueError(f"Version {self.version} not supported")

        self. keys_description = {
            'MaxAbsEStateIndex': 'Maximum absolute value of EState indices',
            'MaxEStateIndex': 'Maximum value of EState indices',
            'MinAbsEStateIndex': 'Minimum absolute value of EState indices',
            'MinEStateIndex': 'Minimum value of EState indices',
            'qed': 'Quantitative estimate of drug-likeness',
            'SPS': 'Sum of EState indices for all atoms',
            'MolWt': 'Molecular weight',
            'HeavyAtomMolWt': 'Molecular weight of the molecule ignoring hydrogens',
            'ExactMolWt': 'Exact molecular weight',
            'NumValenceElectrons': 'Number of valence electrons',
            'NumRadicalElectrons': 'Number of radical electrons',
            'MaxPartialCharge': 'Maximum partial charge on any atom',
            'MinPartialCharge': 'Minimum partial charge on any atom',
            'MaxAbsPartialCharge': 'Maximum absolute value of partial charges',
            'MinAbsPartialCharge': 'Minimum absolute value of partial charges',
            'FpDensityMorgan1': 'Morgan fingerprint density (radius 1)',
            'FpDensityMorgan2': 'Morgan fingerprint density (radius 2)',
            'FpDensityMorgan3': 'Morgan fingerprint density (radius 3)',
            'BCUT2D_MWHI': 'Highest BCUT2D descriptor based on atomic weights',
            'BCUT2D_MWLOW': 'Lowest BCUT2D descriptor based on atomic weights',
            'BCUT2D_CHGHI': 'Highest BCUT2D descriptor based on atomic partial charges',
            'BCUT2D_CHGLO': 'Lowest BCUT2D descriptor based on atomic partial charges',
            'BCUT2D_LOGPHI': 'Highest BCUT2D descriptor based on atomic logP values',
            'BCUT2D_LOGPLOW': 'Lowest BCUT2D descriptor based on atomic logP values',
            'BCUT2D_MRHI': 'Highest BCUT2D descriptor based on atomic molar refractivity',
            'BCUT2D_MRLOW': 'Lowest BCUT2D descriptor based on atomic molar refractivity',
            'BalabanJ': 'Balaban\'s J index',
            'BertzCT': 'Bertz\'s CT index',
            'Chi0': 'Molecular connectivity chi index (order 0)',
            'Chi0n': 'Normalized molecular connectivity chi index (order 0)',
            'Chi0v': 'Valence molecular connectivity chi index (order 0)',
            'Chi1': 'Molecular connectivity chi index (order 1)',
            'Chi1n': 'Normalized molecular connectivity chi index (order 1)',
            'Chi1v': 'Valence molecular connectivity chi index (order 1)',
            'Chi2n': 'Normalized molecular connectivity chi index (order 2)',
            'Chi2v': 'Valence molecular connectivity chi index (order 2)',
            'Chi3n': 'Normalized molecular connectivity chi index (order 3)',
            'Chi3v': 'Valence molecular connectivity chi index (order 3)',
            'Chi4n': 'Normalized molecular connectivity chi index (order 4)',
            'Chi4v': 'Valence molecular connectivity chi index (order 4)',
            'HallKierAlpha': 'Hall-Kier alpha modification index',
            'Ipc': 'Information content index (neighborhood symmetry of atom types)',
            'Kappa1': 'Kappa shape index (order 1)',
            'Kappa2': 'Kappa shape index (order 2)',
            'Kappa3': 'Kappa shape index (order 3)',
            'LabuteASA': 'Labute\'s approximate surface area',
            'PEOE_VSA1': 'PEOE VSA descriptor 1',
            'PEOE_VSA10': 'PEOE VSA descriptor 10',
            'PEOE_VSA11': 'PEOE VSA descriptor 11',
            'PEOE_VSA12': 'PEOE VSA descriptor 12',
            'PEOE_VSA13': 'PEOE VSA descriptor 13',
            'PEOE_VSA14': 'PEOE VSA descriptor 14',
            'PEOE_VSA2': 'PEOE VSA descriptor 2',
            'PEOE_VSA3': 'PEOE VSA descriptor 3',
            'PEOE_VSA4': 'PEOE VSA descriptor 4',
            'PEOE_VSA5': 'PEOE VSA descriptor 5',
            'PEOE_VSA6': 'PEOE VSA descriptor 6',
            'PEOE_VSA7': 'PEOE VSA descriptor 7',
            'PEOE_VSA8': 'PEOE VSA descriptor 8',
            'PEOE_VSA9': 'PEOE VSA descriptor 9',
            'SMR_VSA1': 'SMR VSA descriptor 1',
            'SMR_VSA10': 'SMR VSA descriptor 10',
            'SMR_VSA2': 'SMR VSA descriptor 2',
            'SMR_VSA3': 'SMR VSA descriptor 3',
            'SMR_VSA4': 'SMR VSA descriptor 4',
            'SMR_VSA5': 'SMR VSA descriptor 5',
            'SMR_VSA6': 'SMR VSA descriptor 6',
            'SMR_VSA7': 'SMR VSA descriptor 7',
            'SMR_VSA8': 'SMR VSA descriptor 8',
            'SMR_VSA9': 'SMR VSA descriptor 9',
            'SlogP_VSA1': 'SlogP VSA descriptor 1',
            'SlogP_VSA10': 'SlogP VSA descriptor 10',
            'SlogP_VSA11': 'SlogP VSA descriptor 11',
            'SlogP_VSA12': 'SlogP VSA descriptor 12',
            'SlogP_VSA2': 'SlogP VSA descriptor 2',
            'SlogP_VSA3': 'SlogP VSA descriptor 3',
            'SlogP_VSA4': 'SlogP VSA descriptor 4',
            'SlogP_VSA5': 'SlogP VSA descriptor 5',
            'SlogP_VSA6': 'SlogP VSA descriptor 6',
            'SlogP_VSA7': 'SlogP VSA descriptor 7',
            'SlogP_VSA8': 'SlogP VSA descriptor 8',
            'SlogP_VSA9': 'SlogP VSA descriptor 9',
            'TPSA': 'Topological polar surface area',
            'EState_VSA1': 'EState VSA descriptor 1',
            'EState_VSA10': 'EState VSA descriptor 10',
            'EState_VSA11': 'EState VSA descriptor 11',
            'EState_VSA2': 'EState VSA descriptor 2',
            'EState_VSA3': 'EState VSA descriptor 3',
            'EState_VSA4': 'EState VSA descriptor 4',
            'EState_VSA5': 'EState VSA descriptor 5',
            'EState_VSA6': 'EState VSA descriptor 6',
            'EState_VSA7': 'EState VSA descriptor 7',
            'EState_VSA8': 'EState VSA descriptor 8',
            'EState_VSA9': 'EState VSA descriptor 9',
            'VSA_EState1': 'VSA EState descriptor 1',
            'VSA_EState10': 'VSA EState descriptor 10',
            'VSA_EState2': 'VSA EState descriptor 2',
            'VSA_EState3': 'VSA EState descriptor 3',
            'VSA_EState4': 'VSA EState descriptor 4',
            'VSA_EState5': 'VSA EState descriptor 5',
            'VSA_EState6': 'VSA EState descriptor 6',
            'VSA_EState7': 'VSA EState descriptor 7',
            'VSA_EState8': 'VSA EState descriptor 8',
            'VSA_EState9': 'VSA EState descriptor 9',
            'FractionCSP3': 'Fraction of C atoms that are SP3 hybridized',
            'HeavyAtomCount': 'Number of heavy atoms (non-hydrogen atoms) in the molecule',
            'NHOHCount': 'Number of hydroxyl (-OH) and amine (-NH) groups in the molecule',
            'NOCount': 'Total number of oxygen and nitrogen atoms in the molecule',
            'NumAliphaticCarbocycles': 'Number of aliphatic carbocycles in the molecule',
            'NumAliphaticHeterocycles': 'Number of aliphatic heterocycles (containing at least one non-carbon atom) in the molecule',
            'NumAliphaticRings': 'Total number of aliphatic rings in the molecule',
            'NumAromaticCarbocycles': 'Number of aromatic carbocycles in the molecule',
            'NumAromaticHeterocycles': 'Number of aromatic heterocycles in the molecule',
            'NumAromaticRings': 'Total number of aromatic rings in the molecule',
            'NumHAcceptors': 'Number of hydrogen bond acceptors in the molecule',
            'NumHDonors': 'Number of hydrogen bond donors in the molecule',
            'NumHeteroatoms': 'Number of heteroatoms (non-carbon and non-hydrogen atoms) in the molecule',
            'NumRotatableBonds': 'Number of rotatable bonds in the molecule',
            'NumSaturatedCarbocycles': 'Number of saturated carbocycles in the molecule',
            'NumSaturatedHeterocycles': 'Number of saturated heterocycles in the molecule',
            'NumSaturatedRings': 'Total number of saturated rings in the molecule',
            'RingCount': 'Total number of rings in the molecule',
            'MolLogP': 'LogP value of the molecule, an estimate of its lipophilicity',
            'MolMR': 'Molecular mass of the molecule',
            'fr_Al_COO': 'Aliphatic chain containing a carboxylic acid group',
            'fr_Al_OH': 'Aliphatic chain containing an alcohol group',
            'fr_Al_OH_noTert': 'Aliphatic chain containing a non-tertiary alcohol group',
            'fr_ArN': 'Functional group containing nitrogen on an aromatic ring',
            'fr_Ar_COO': 'Aromatic chain containing a carboxylic acid group',
            'fr_Ar_N': 'Functional group containing aromatic nitrogen',
            'fr_Ar_NH': 'Functional group containing aromatic NH',
            'fr_Ar_OH': 'Functional group containing aromatic alcohol',
            'fr_COO': 'Functional group containing a carboxylic acid moiety',
            'fr_COO2': 'Functional group containing a dicarboxylic acid moiety',
            'fr_C_O': 'Functional group containing a carbon-oxygen bond',
            'fr_C_O_noCOO': 'Functional group containing a non-carboxylic carbon-oxygen bond',
            'fr_C_S': 'Functional group containing a carbon-sulfur bond',
            'fr_HOCCN': 'Functional group containing a hydroxy-nitrile moiety',
            'fr_Imine': 'Functional group containing an imine moiety',
            'fr_NH0': 'Functional group containing a trivalent nitrogen (without hydrogen)',
            'fr_NH1': 'Functional group containing a trivalent nitrogen (with one hydrogen)',
            'fr_NH2': 'Functional group containing a divalent nitrogen (with two hydrogens)',
            'fr_N_O': 'Functional group containing a nitrogen-oxygen bond',
            'fr_Ndealkylation1': 'Indicates where primary dealkylation reaction may occur',
            'fr_Ndealkylation2': 'Indicates where secondary dealkylation reaction may occur',
            'fr_Nhpyrrole': 'Functional group containing pyrrole-like nitrogen',
            'fr_SH': 'Functional group containing a thiol moiety',
            'fr_aldehyde': 'Functional group containing an aldehyde moiety',
            'fr_alkyl_carbamate': 'Functional group containing an alkyl carbamate',
            'fr_alkyl_halide': 'Functional group containing an alkyl halide',
            'fr_allylic_oxid': 'Functional group containing an allylic oxidation',
            'fr_amide': 'Functional group containing an amide moiety',
            'fr_amidine': 'Functional group containing an amidine moiety',
            'fr_aniline': 'Functional group containing an aniline moiety',
            'fr_aryl_methyl': 'Functional group containing an aryl methyl',
            'fr_azide': 'Functional group containing an azide moiety',
            'fr_azo': 'Functional group containing an azo moiety',
            'fr_barbitur': 'Functional group containing a barbiturate moiety',
            'fr_benzene': 'Functional group containing a benzene ring',
            'fr_benzodiazepine': 'Functional group containing a benzodiazepine moiety',
            'fr_bicyclic': 'Functional group containing a bicyclic structure',
            'fr_diazo': 'Functional group containing a diazo moiety',
            'fr_dihydropyridine': 'Functional group containing a dihydropyridine moiety',
            'fr_epoxide': 'Functional group containing an epoxide moiety',
            'fr_ester': 'Functional group containing an ester moiety',
            'fr_ether': 'Functional group containing an ether moiety',
            'fr_furan': 'Functional group containing a furan ring',
            'fr_guanido': 'Functional group containing a guanido moiety',
            'fr_halogen': 'Functional group containing a halogen atom',
            'fr_hdrzine': 'Functional group containing a hydrazine moiety',
            'fr_hdrzone': 'Functional group containing a hydrazone moiety',
            'fr_imidazole': 'Functional group containing an imidazole ring',
            'fr_imide': 'Functional group containing an imide moiety',
            'fr_isocyan': 'Functional group containing an isocyanate moiety',
            'fr_isothiocyan': 'Functional group containing an isothiocyanate moiety',
            'fr_ketone': 'Functional group containing a ketone moiety',
            'fr_ketone_Topliss': 'Ketone moiety in Topliss mode',
            'fr_lactam': 'Functional group containing a lactam moiety',
            'fr_lactone': 'Functional group containing a lactone moiety',
            'fr_methoxy': 'Functional group containing a methoxy moiety',
            'fr_morpholine': 'Functional group containing a morpholine ring',
            'fr_nitrile': 'Functional group containing a nitrile moiety',
            'fr_nitro': 'Functional group containing a nitro moiety',
            'fr_nitro_arom': 'Functional group containing an aromatic nitro moiety',
            'fr_nitro_arom_nonortho': 'Functional group containing a non-ortho aromatic nitro moiety',
            'fr_nitroso': 'Functional group containing a nitroso moiety',
            'fr_oxazole': 'Functional group containing an oxazole ring',
            'fr_oxime': 'Functional group containing an oxime moiety',
            'fr_para_hydroxylation': 'Functional group containing para-hydroxylation',
            'fr_phenol': 'Functional group containing a phenol moiety',
            'fr_phenol_noOrthoHbond': 'Phenol moiety without ortho hydrogen bonding',
            'fr_phos_acid': 'Functional group containing a phosphonic acid moiety',
            'fr_phos_ester': 'Functional group containing a phosphoric ester moiety',
            'fr_piperdine': 'Functional group containing a piperidine ring',
            'fr_piperzine': 'Functional group containing a piperazine ring',
            'fr_priamide': 'Functional group containing a primary amide',
            'fr_prisulfonamd': 'Functional group containing a primary sulfonamide',
            'fr_pyridine': 'Functional group containing a pyridine ring',
            'fr_quatN': 'Functional group containing a quaternary ammonium nitrogen',
            'fr_sulfide': 'Functional group containing a sulfide moiety',
            'fr_sulfonamd': 'Functional group containing a sulfonamide moiety',
            'fr_sulfone': 'Functional group containing a sulfone moiety',
            'fr_term_acetylene': 'Functional group containing a terminal alkyne',
            'fr_tetrazole': 'Functional group containing a tetrazole ring',
            'fr_thiazole': 'Functional group containing a thiazole ring',
            'fr_thiocyan': 'Functional group containing a thiocyanate moiety',
            'fr_thiophene': 'Functional group containing a thiophene ring',
            'fr_unbrch_alkane': 'Functional group containing an unbranched alkane',
            'fr_urea': 'Functional group containing a urea moiety'
        }

    def load_prior_knowledge_features(self, smiles_list):
        prior_knowledge = []
        for smiles in smiles_list:
            molecule = Chem.MolFromSmiles(smiles)
            descriptors = {name: func(molecule) for name, func in Descriptors.descList if name in self.prior_keys}
            prior_knowledge.append([f"Property:{self.keys_description[key]}, Value:'{value}'" for key, value in descriptors.items()])
        return prior_knowledge

    def load_prior_descriptions(self):
        return [self.keys_description[name] for name, _ in Descriptors.descList if name in self.prior_keys]


if __name__ == '__main__':
    lib = PriorKnowledgeLib(version='all')
    smiles_list = ["CN(c1ccccc1)c1ccccc1C(=O)NCC1(O)CCOCC1", "CCO", "CCN", "CCO", "CCN"]
    ret = lib.load_prior_knowledge_features(smiles_list)
    tokenized_text = []
    for item in ret:
        tokenized_text.append(clip.tokenize(item))